font_family Hasklug Nerd Font
font_size 11
background_opacity 0.95

cursor_shape beam
cursor_trail 1

window_margin 22
confirm_os_window_close 0

shell fish


# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME
