config_version = 8

[bar.default]
background_opacity = 0.90999997965991497
capsule = true
capsule_padding = 5.0
capsule_thickness = 0.86999998427927494
center = [ "taskbar", "launcher" ]
concave_edge_corners = false
end = [
    "keyboard_layout",
    "tray",
    "notifications",
    "group:g3",
    "group:g2",
    "group:g1",
    "brightness",
    "battery",
    "wallpaper",
    "widget",
    "keybinds",
    "widget_2"
]
font_family = "Hasklug Nerd Font"
margin_ends = 300
padding = 2
radius = 37
scale = 0.90000000596046448
start = [ "clock", "sysmon", "media" ]
thickness = 24

    [[bar.default.capsule_group]]
    enabled = true
    fill = "surface_variant"
    id = "g1"
    members = [ "volume", "input_volume" ]
    opacity = 1.0
    padding = 5.0

    [[bar.default.capsule_group]]
    enabled = true
    fill = "surface_variant"
    id = "g2"
    members = [ "network", "bluetooth" ]
    opacity = 1.0
    padding = 5.0

    [[bar.default.capsule_group]]
    enabled = true
    fill = "surface_variant"
    id = "g3"
    members = [ "clipboard", "notes" ]
    opacity = 1.0
    padding = 5.0

[control_center]
hidden_tabs = [ "weather" ]
sidebar = "full"

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@HDMI-A-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[notification]
border = false
position = "top_right"

[osd]
offset_x = 16
position = "top_right"

[plugin_settings."yuuto/arch-updater"]
aur_helper = "off"
auto_check_hours = 1
flatpak_enabled = false

[plugins]
enabled = [
    "noctalia/notes",
    "cleboost/zed-provider",
    "yocraft/web-launcher",
    "tadomika_ari/config-swap",
    "kenn/keybind-cheatsheet",
    "thepunkoff/pomodoro",
    "yuuto/arch-updater"
]

[shell]
avatar_path = "/home/void/Pictures/avatar.png"
card_borders = false
corner_radius_scale = 0.70000001043081284
font_family = "Hasklug Nerd Font"
lang = "en"
polkit_agent = true

    [shell.greeter_sync]
    auto_sync = true

    [shell.launcher]
    provider_prefix = ">"

        [shell.launcher.providers.calculator]
        prefix = ""

        [shell.launcher.providers.emoji]
        prefix = ""

        [shell.launcher.providers.session]
        prefix = ""

    [shell.panel]
    clipboard_placement = "attached"
    open_near_click_clipboard = true
    open_near_click_control_center = true
    open_near_click_wallpaper = true
    polkit_placement = "attached"
    transparency_mode = "glass"

    [shell.screenshot]
    remember_last_region = true

[theme]
builtin = "Ayu"

[wallpaper]
transition = [ "disc", "fade", "honeycomb", "stripes", "wipe", "zoom" ]
transition_on_startup = true

    [wallpaper.default]
    path = "/home/void/Pictures/Wallpapers/candylove3d-1758795308.webp"

    [wallpaper.last]
    path = "/home/void/Pictures/Wallpapers/candylove3d-1758795308.webp"

    [wallpaper.monitors.HDMI-A-1]
    path = "/home/void/Pictures/Wallpapers/candylove3d-1758795308.webp"

[widget.clock]
format = "{:%H:%M %a, %b %d}"

[widget.keybinds]
type = "kenn/keybind-cheatsheet:keybinds"

[widget.keyboard_layout]
capsule = true
capsule_padding = 8
show_icon = false

[widget.media]
hide_when_no_media = true
max_length = 200
title_scroll = "on_hover"

[widget.network]
show_label = false

[widget.notes]
type = "noctalia/notes:notes"

[widget.sysmon]
display = "text"
stat = "cpu_temp"

[widget.taskbar]
group_by_workspace = true
hide_empty_workspaces = true
inactive_opacity = 0.71999999999999997
show_active_indicator = false

[widget.widget]
type = "yuuto/arch-updater:widget"

[widget.widget_2]
type = "thepunkoff/pomodoro:widget"

[widget.workspaces]
enabled = false